/* This file is generated by scripts/extract-office-sprites.ts. */

export type OfficeAsset = {
  id: string;
  name: string;
  src: string;
  width: number;
  height: number;
};

export const OFFICE_ASSETS = [
  {
    "id": "desk",
    "name": "Desk",
    "src": "/assets/office/items/desk.png",
    "width": 244,
    "height": 142
  },
  {
    "id": "chair",
    "name": "Chair",
    "src": "/assets/office/items/chair.png",
    "width": 104,
    "height": 158
  },
  {
    "id": "plant",
    "name": "Plant",
    "src": "/assets/office/items/plant.png",
    "width": 106,
    "height": 154
  },
  {
    "id": "printer",
    "name": "Printer",
    "src": "/assets/office/items/printer.png",
    "width": 222,
    "height": 162
  },
  {
    "id": "shelf",
    "name": "Shelf",
    "src": "/assets/office/items/shelf.png",
    "width": 164,
    "height": 160
  },
  {
    "id": "lamp",
    "name": "Lamp",
    "src": "/assets/office/items/lamp.png",
    "width": 66,
    "height": 108
  },
  {
    "id": "sofa",
    "name": "Sofa",
    "src": "/assets/office/items/sofa.png",
    "width": 136,
    "height": 104
  },
  {
    "id": "coffee",
    "name": "Coffee",
    "src": "/assets/office/items/coffee.png",
    "width": 90,
    "height": 88
  },
  {
    "id": "meeting-table",
    "name": "Meeting table",
    "src": "/assets/office/items/meeting-table.png",
    "width": 314,
    "height": 124
  },
  {
    "id": "wall-clock",
    "name": "Wall clock",
    "src": "/assets/office/items/wall-clock.png",
    "width": 104,
    "height": 106
  },
  {
    "id": "whiteboard",
    "name": "Whiteboard",
    "src": "/assets/office/items/whiteboard.png",
    "width": 154,
    "height": 118
  },
  {
    "id": "water-dispenser",
    "name": "Water dispenser",
    "src": "/assets/office/items/water-dispenser.png",
    "width": 88,
    "height": 258
  },
  {
    "id": "filing-cabinet",
    "name": "Filing cabinet",
    "src": "/assets/office/items/filing-cabinet.png",
    "width": 116,
    "height": 168
  },
  {
    "id": "coffee-machine",
    "name": "Coffee machine",
    "src": "/assets/office/items/coffee-machine.png",
    "width": 152,
    "height": 174
  },
  {
    "id": "door",
    "name": "Office door",
    "src": "/assets/office/items/door.png",
    "width": 120,
    "height": 174
  }
] as const satisfies readonly OfficeAsset[];

const officeAssetsById = new Map<string, OfficeAsset>(
  OFFICE_ASSETS.map((asset) => [asset.id, asset]),
);

export function getOfficeAsset(id: string): OfficeAsset | null {
  return officeAssetsById.get(id) ?? null;
}
