import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import sharp from "sharp";

type SpriteDefinition = {
  height: number;
  id: string;
  name: string;
  width: number;
  x: number;
  y: number;
};

const SPRITES = [
  { id: "desk", name: "Desk", x: 24, y: 338, width: 244, height: 142 },
  { id: "chair", name: "Chair", x: 568, y: 330, width: 104, height: 158 },
  { id: "plant", name: "Plant", x: 684, y: 332, width: 106, height: 154 },
  { id: "printer", name: "Printer", x: 748, y: 514, width: 222, height: 162 },
  { id: "shelf", name: "Shelf", x: 454, y: 514, width: 164, height: 160 },
  { id: "lamp", name: "Lamp", x: 360, y: 526, width: 66, height: 108 },
  { id: "sofa", name: "Sofa", x: 22, y: 690, width: 136, height: 104 },
  { id: "coffee", name: "Coffee", x: 526, y: 690, width: 90, height: 88 },
  {
    id: "meeting-table",
    name: "Meeting table",
    x: 286,
    y: 814,
    width: 314,
    height: 124,
  },
  {
    id: "wall-clock",
    name: "Wall clock",
    x: 790,
    y: 124,
    width: 104,
    height: 106,
  },
  {
    id: "whiteboard",
    name: "Whiteboard",
    x: 842,
    y: 690,
    width: 154,
    height: 118,
  },
  {
    id: "water-dispenser",
    name: "Water dispenser",
    x: 802,
    y: 226,
    width: 88,
    height: 258,
  },
  {
    id: "filing-cabinet",
    name: "Filing cabinet",
    x: 624,
    y: 508,
    width: 116,
    height: 168,
  },
  {
    id: "coffee-machine",
    name: "Coffee machine",
    x: 848,
    y: 830,
    width: 152,
    height: 174,
  },
  {
    id: "door",
    name: "Office door",
    x: 154,
    y: 806,
    width: 120,
    height: 174,
  },
] as const satisfies readonly SpriteDefinition[];

const projectRoot = process.cwd();
const spriteSheetPath = path.join(
  projectRoot,
  "public",
  "assets",
  "office",
  "spritesheet.png",
);
const outputDirectory = path.join(
  projectRoot,
  "public",
  "assets",
  "office",
  "items",
);
const registryPath = path.join(
  projectRoot,
  "src",
  "features",
  "office",
  "assets",
  "office-assets.ts",
);

function assertSpriteInsideImage(
  sprite: SpriteDefinition,
  imageWidth: number,
  imageHeight: number,
): void {
  const right = sprite.x + sprite.width;
  const bottom = sprite.y + sprite.height;

  if (
    sprite.x < 0 ||
    sprite.y < 0 ||
    sprite.width <= 0 ||
    sprite.height <= 0 ||
    right > imageWidth ||
    bottom > imageHeight
  ) {
    throw new Error(
      `Sprite "${sprite.id}" crop is outside the spritesheet bounds.`,
    );
  }
}

function createRegistrySource(sprites: readonly SpriteDefinition[]): string {
  const assets = sprites.map((sprite) => ({
    id: sprite.id,
    name: sprite.name,
    src: `/assets/office/items/${sprite.id}.png`,
    width: sprite.width,
    height: sprite.height,
  }));

  return `/* This file is generated by scripts/extract-office-sprites.ts. */

export type OfficeAsset = {
  id: string;
  name: string;
  src: string;
  width: number;
  height: number;
};

export const OFFICE_ASSETS = ${JSON.stringify(assets, null, 2)} as const satisfies readonly OfficeAsset[];

const officeAssetsById = new Map<string, OfficeAsset>(
  OFFICE_ASSETS.map((asset) => [asset.id, asset]),
);

export function getOfficeAsset(id: string): OfficeAsset | null {
  return officeAssetsById.get(id) ?? null;
}
`;
}

async function extractOfficeSprites(): Promise<void> {
  const metadata = await sharp(spriteSheetPath).metadata();
  const imageWidth = metadata.width;
  const imageHeight = metadata.height;

  if (!imageWidth || !imageHeight) {
    throw new Error("Unable to read spritesheet dimensions.");
  }

  await mkdir(outputDirectory, { recursive: true });
  await mkdir(path.dirname(registryPath), { recursive: true });

  for (const sprite of SPRITES) {
    assertSpriteInsideImage(sprite, imageWidth, imageHeight);

    const outputPath = path.join(outputDirectory, `${sprite.id}.png`);

    await sharp(spriteSheetPath)
      .extract({
        left: sprite.x,
        top: sprite.y,
        width: sprite.width,
        height: sprite.height,
      })
      .png()
      .toFile(outputPath);

    console.log(
      `Extracted ${sprite.id} -> ${path.relative(projectRoot, outputPath)}`,
    );
  }

  await writeFile(registryPath, createRegistrySource(SPRITES), "utf8");
  console.log(`Generated ${path.relative(projectRoot, registryPath)}`);
}

void extractOfficeSprites().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
